url:                    http://localhost/kostyanetsky.me
language_code:          en
mirror_url:             http://localhost/kostyanetsky.ru
mirror_language_code:   ru
github_repository:      vkostyanetsky/kostyanetsky.me