1c:           "1ะก"
work:         "work"
english:      "English"
meanwhile:    "meanwhile"
sport:        "sport"
books:        "books"
videogames:   "videogames"
mssql:        "MS SQL"
films:        "films"
webdev:       "webdev"
bash:         "bash"
family:       "family"
optimization: "optimization"
workplace:    "workplace"
code-smell:   "code smell"
powershell:   "PowerShell"
done:         "done"
pgsql:        "PostgreSQL"
python:       "Python"
blog:         "blog"
nodejs:       "Node.js"
bitrix:       "Bitrix"
swagger:      "Swagger"
typescript:   "TypeScript"
obsidian:     "Obsidian"