1c:           "1ะก"
work:         "Work"
english:      "English"
meanwhile:    "Meanwhile"
sport:        "Sport"
books:        "Books"
videogames:   "Videogames"
mssql:        "MS SQL"
films:        "Films"
webdev:       "Webdev"
bash:         "Bash"
family:       "Family"
optimization: "Optimization"
workplace:    "Workplace"
code-smell:   "Code Smell"
powershell:   "PowerShell"
done:         "Done"
pgsql:        "PostgreSQL"
python:       "Python"
blog:         "Blog"
nodejs:       "Node.js"
bitrix:       "Bitrix"
swagger:      "Swagger"
javascript:   "JavaScript"
typescript:   "TypeScript"
obsidian:     "Obsidian"
georgia:      "Georgia"
ai:           "AI"
3d:           "3D"
